spring:
  datasource:
    gray:
      url: jdbc:mysql://localhost:3306/gray?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    gray:
      database: 1
      host: localhost
      port: 6379